name: Auto link PR to Issues

on:
  pull_request:
    types: [opened, edited, synchronize, closed]

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  call-linker:
    uses: Test-unito/demo-repository/blob/main/.github/workflows/use-pr-linker.yml
    secrets:
      CROSS_REPO_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
